sudo: true
language: haskell

git:
  depth: 1

cabal: "3.0"

cache:
  directories:
  - "$HOME/.cabal/store"

matrix:
  include:
  - ghc: 8.4.4
  - ghc: 8.6.5
  - ghc: 8.8.3


install:
  - |
    ghc --version
    cabal --version
    cabal new-update
    cabal new-configure
    cabal new-build --enable-tests

script:
  - cabal new-test
  # HLint check
  - curl -sSL https://raw.github.com/ndmitchell/neil/master/misc/travis.sh | sh -s -- hlint .

notifications:
  email: false
